# Generated by Django 6.1 on 2026-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('start_year', models.CharField(max_length=50)),
                ('end_year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('is_fresher_notice', models.BooleanField(default=False, help_text='Check if this entry highlights fresher / open to opportunities status')),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='extra_sections/')),
                ('button_text', models.CharField(blank=True, default='', max_length=100)),
                ('button_url', models.CharField(blank=True, default='', max_length=300)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Poovarasan', max_length=120)),
                ('title', models.CharField(default='Python Full Stack Developer', max_length=150)),
                ('hero_subtitle', models.TextField(default='I am a passionate Python Full Stack Developer focused on building practical, responsive, and user-friendly web applications.')),
                ('bio', models.TextField(blank=True, default='')),
                ('career_objective', models.TextField(blank=True, default='')),
                ('developer_background', models.TextField(blank=True, default='')),
                ('interests', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('email', models.EmailField(blank=True, default='poovarasan.dev@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+91 9876543210', max_length=50)),
                ('location', models.CharField(blank=True, default='Tamil Nadu, India', max_length=150)),
                ('github', models.URLField(blank=True, default='https://github.com/Poovarasan')),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com/in/poovarasan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated technologies, e.g. React, Django, SQLite', max_length=300)),
                ('github_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('category', models.CharField(default='Full Stack', max_length=100)),
                ('project_date', models.CharField(blank=True, default='2025', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Other', 'Other')], default='Frontend', max_length=50)),
                ('level', models.IntegerField(default=85, help_text='Proficiency percentage (0-100)')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
